# 無効にするルール
disabled_rules:
  - object_literal
  - todo
  #  - cyclomatic_complexity
  - function_parameter_count
  - force_try
  #  - nesting
  - valid_ibinspectable
  - unused_optional_binding

# デフォルトルール以外でopt-inから適用させるルールの設定
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  #- conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  #- discouraged_object_literal # オブジェクトリテラルを使いたいため
  - discouraged_optional_boolean
  #- discouraged_optional_collection
  - empty_count
  - empty_string
  - empty_xctest_method
  #- explicit_acl # できる限りACLを省略したいため
  #- explicit_enum_raw_value # ローバリューを省略することもあるため
  - explicit_init
  #- explicit_self # 関数は `self.` を付けずに呼び出したいため
  #- explicit_top_level_acl # できる限りACLを省略したいため
  #- explicit_type_interface # できる限り型推論したいため
  #- extension_access_modifier # このルールの意味を理解していないため
  - fallthrough
  - fatal_error_message
  #- file_header # このルールの意味を理解していないため
  - file_name
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  #- implicitly_unwrapped_optional # VIPERで変数を `!` で定義したいため
  - joined_default_parameter
  - last_where
  - legacy_random
  #- let_var_whitespace # 空白行を設けたくないこともあるため
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  #- multiline_arguments # 引数は同じ行に2つ入れたいこともあるため
  #- multiline_arguments_brackets # 括弧で行を増やしたくないため
  #- multiline_function_chains # 関数の呼び出しは同じ行に2つ入れたいこともあるため
  #- multiline_literal_brackets # 括弧で行を増やしたくないため
  #- multiline_parameters # 引数は同じ行に2つ入れたいこともあるため
  #- multiline_parameters_brackets # 括弧で行を増やしたくないため
  - nimble_operator
  #- no_extension_access_modifier # エクステンションにACLを設定したいことがあるため
  # - no_grouping_extension # グループ化するためにエクステンションを使わないため
  - nslocalizedstring_key
  #- number_separator # 数字を `_` で区切りたくないため
  #- object_literal # リテラルで生成したくないこともあるため
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  #- prefixed_toplevel_constant # 定数のプリフィックスに `k` を付けたくないため
  - private_action
  #- private_outlet
  #- prohibited_interface_builder # ストーリーボードを使ってビューを生成したいため
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  #- required_deinit # できる限りデイニシャライザを省略したいため
  - required_enum_case
  - single_test_class
  - sorted_first_last
  #- sorted_imports # インポート文をアルファベット順以外に並び替えたいこともあるため
  - static_operator
  - strict_fileprivate
  #- strong_iboutlet # `@IBOutlet` を `weak` で定義したいこともあるため
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  #- vertical_whitespace_between_cases # Switch文のケース間に空白行を設けたくないこともあるため
  #- vertical_whitespace_closing_braces # 中括弧を閉じる前に空白行を設けたいことがあるため
  #- vertical_whitespace_opening_braces # 中括弧を開く前に空白行を設けたいことがあるため
  - xct_specific_matcher
  - yoda_condition

# SwiftLintの適用から外すディレクトリ
# (UnitTestやUITestもある場合は修正されますので入れます)
excluded:
  - R.generated.swift
  - Carthage
  - fastlane
  - firebase
  - Pods
  - ArchitectureSample01Tests
  - ArchitectureSample01UITests

# 1行あたりの文字数制限など
line_length:
  warning: 200 # 150
  error: 1000 # Remove
  ignores_comments: true
type_body_length:
  - 1000 # 300 # warning
  - 1000 # 400 # error
type_name:
  min_length: 1
  max_length: 75
function_body_length:
  warning: 400
  error: 500
file_length:
  warning: 500
  error: 1200

identifier_name:
  min_length: # only min_length
  error: 2 # only error
  excluded: # excluded via string array
    - id
    - URL
    - x
    - y
    - vc
    - on
  reporter: "xcode"

# SwiftLint
# https://github.com/realm/SwiftLint
# JP - doc
# https://qiita.com/kagemiku/items/80e6d905dc0059c342b3
