# 無効にするルール
disabled_rules:
  - object_literal
  - todo
  #  - cyclomatic_complexity
  - function_parameter_count
  - force_try
  #  - nesting
  - valid_ibinspectable

  # opt-inルールの中で無効にするルール
  - conditional_returns_on_newline # ガード文などは簡潔に一行で記述したいため
  - discouraged_optional_collection # PHImageManagerの既存仕様のため
  - explicit_enum_raw_value # 暗黙的なraw値で問題ないため
  - explicit_type_interface # 型推論を利用したいため
  - fatal_error_message # メッセージは不要なため
  - file_header # ヘッダには特に決まりがないため
  - lower_acl_than_parent # 対応不可のため
  - no_extension_access_modifier # extension_access_modifierを優先するため
  - no_grouping_extension # グルーピングにextensionを利用したいため
  - strict_fileprivate # fileprivateを利用したいため
  - switch_case_on_newline # caseと同じ行に記述したいため
  - trailing_closure # RxSwiftのOnNextでwarningが出るため

# デフォルトルール以外でopt-inから適用させるルールの設定
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# SwiftLintの適用から外すディレクトリ
# (UnitTestやUITestもある場合は修正されますので入れます)
excluded:
  #  - valu/SupportingFiles/R.generated.swift
  - Carthage
  - fastlane
  - firebase
  - Pods
  - ArchitectureSample01Tests
  - ArchitectureSample01UITests

# 1行あたりの文字数制限など
line_length:
  warning: 2000 # 150
  error: 2000 # Remove
  ignores_comments: true
type_body_length:
  - 1000 # 300 # warning
  - 1000 # 400 # error
type_name:
  min_length: 1
  max_length: 75
function_body_length:
  warning: 400
  error: 500
file_length:
  warning: 500
  error: 1200

identifier_name:
  min_length: # only min_length
  error: 2 # only error
  excluded: # excluded via string array
    - id
    - URL
    - x
    - y
    - vc
    - on
  reporter: "xcode"
# SwiftLint
# https://github.com/realm/SwiftLint
# JP - doc
# https://qiita.com/kagemiku/items/80e6d905dc0059c342b3
